### 식당 목록 조회
GET http://localhost:8080/api/restaurants
Content-Type: application/json

### 식당 조회

### 식당 등록
POST http://localhost:8080/api/owner/restaurants
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5ZjI4YjMzZS1jNjIyLTQ4OWQtOTI2YS00OWVmMWNlN2ZhYTAiLCJyb2xlIjoiT1dORVIiLCJpYXQiOjE3NzkzMzcxMTAsImV4cCI6MTc3OTM0MDcxMH0.WFc-9j63RP3EsNyPSgtagAdomWCHya8KKpG5q3y8LPbSOUdO-0pAkZ28HfLvnziwulPPDalFX7sbsGVPMemaew

{
  "name": "Owner1 식당",
  "phone": "010-1111-1111",
  "address": "경기도 성남시 분당구 판교로",
  "latitude": 37.401674,
  "longitude": 127.101081,
  "category": "KOREAN",
  "minOrderAmount": 1,
  "deliveryFee": 10000,
  "estimatedDeliveryMinutes": 15
}

### 식당 업데이트
PUT http://localhost:8080/api/owner/restaurants/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5ZjI4YjMzZS1jNjIyLTQ4OWQtOTI2YS00OWVmMWNlN2ZhYTAiLCJyb2xlIjoiT1dORVIiLCJpYXQiOjE3NzkzMzcxMTAsImV4cCI6MTc3OTM0MDcxMH0.WFc-9j63RP3EsNyPSgtagAdomWCHya8KKpG5q3y8LPbSOUdO-0pAkZ28HfLvnziwulPPDalFX7sbsGVPMemaew

{
  "name": "Owner1 식당1",
  "phone": "010-1111-1111",
  "address": "경기도 성남시 분당구 판교로1",
  "latitude": 37.401674,
  "longitude": 127.101081,
  "minOrderAmount": 2,
  "deliveryFee": 11000,
  "estimatedDeliveryMinutes": 16
}

### 식당 영업 시작
PATCH http://localhost:8080/api/owner/restaurants/1/open
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5ZjI4YjMzZS1jNjIyLTQ4OWQtOTI2YS00OWVmMWNlN2ZhYTAiLCJyb2xlIjoiT1dORVIiLCJpYXQiOjE3NzkzMzcxMTAsImV4cCI6MTc3OTM0MDcxMH0.WFc-9j63RP3EsNyPSgtagAdomWCHya8KKpG5q3y8LPbSOUdO-0pAkZ28HfLvnziwulPPDalFX7sbsGVPMemaew

### 식당 영업 종료
PATCH http://localhost:8080/api/owner/restaurants/1/close
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5ZjI4YjMzZS1jNjIyLTQ4OWQtOTI2YS00OWVmMWNlN2ZhYTAiLCJyb2xlIjoiT1dORVIiLCJpYXQiOjE3NzkzMzcxMTAsImV4cCI6MTc3OTM0MDcxMH0.WFc-9j63RP3EsNyPSgtagAdomWCHya8KKpG5q3y8LPbSOUdO-0pAkZ28HfLvnziwulPPDalFX7sbsGVPMemaew

### 나의 식당 목록
GET http://localhost:8080/api/owner/restaurants
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5ZjI4YjMzZS1jNjIyLTQ4OWQtOTI2YS00OWVmMWNlN2ZhYTAiLCJyb2xlIjoiT1dORVIiLCJpYXQiOjE3NzkzMzcxMTAsImV4cCI6MTc3OTM0MDcxMH0.WFc-9j63RP3EsNyPSgtagAdomWCHya8KKpG5q3y8LPbSOUdO-0pAkZ28HfLvnziwulPPDalFX7sbsGVPMemaew
